database:
  user: 'postgres'
  password: 'postgresql'
  host: '10.222.6.8'
  port: '5433'
  database: 'osm'

http_server:
  host: ''
  port: 8005

tables:
  lakes:
    table: 'ne_10m_lakes'
    srid: 3857
    geomColumn: 'wkb_geometry'
    attrColumns: 'ogc_fid, name'
    min_zoom: 0
    max_zoom: 16
    area_thresholds: 
    # https://github.com/mapbox/postgis-vt-util/blob/master/src/ZRes.sql
      - { zoom: 0, area: 16000000000 }
      - { zoom: 1, area: 4000000000 }
      - { zoom: 2, area: 1000000000 }
      - { zoom: 4, area: 256000000 }
      - { zoom: 6, area: 2048000 }
      - { zoom: 8, area: 1024000 }
      - { zoom: 10, area: 512000 }
      - { zoom: 12, area: 256000 }
      - { zoom: 14, area: 128000 }
      - { zoom: 16, area: 64000 }
      - { zoom: 18, area: 32000 }
      - { zoom: 20, area: 16000 }
      - { zoom: 22, area: 0 }
  parks:
    table: 'osm_park_polygon'
    srid: 4326
    geomColumn: 'geometry'
    attrColumns: 'id, name'
    min_zoom: 8
    max_zoom: 16

  poi:
    table: 'osm_poi_polygon'
    srid: 4326
    geomColumn: 'geometry'
    attrColumns: 'id, name'
    min_zoom: 10
    max_zoom: 16

  highway:
    table: 'osm_highway_linestring'
    srid: 4326
    geomColumn: 'geometry'
    attrColumns: 'id, name, level'
    min_zoom: 6
    max_zoom: 16
  
  road:
    table: 'ne_10m_roads'
    srid: 3857
    geomColumn: 'wkb_geometry'
    attrColumns: 'ogc_fid, name, level'
    min_zoom: 5

  city:
    table: 'osm_city_point'
    srid: 4326
    geomColumn: 'geometry'
    attrColumns: 'id, name, rank'
    min_zoom: 10

  